/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AvatarSizes } from "./components/la-avatar/la-button.enums";
import { ButtonSizes, ButtonVariants } from "./components/la-button/la-button.enums";
export namespace Components {
    interface LaAvatar {
        "badge": string;
        "image": string;
        "size": AvatarSizes;
        "text": string;
    }
    interface LaButton {
        /**
          * @Prop animated - animate component shadow on hover *
         */
        "animated": boolean;
        "size": ButtonSizes;
        "variant": ButtonVariants;
    }
}
declare global {
    interface HTMLLaAvatarElement extends Components.LaAvatar, HTMLStencilElement {
    }
    var HTMLLaAvatarElement: {
        prototype: HTMLLaAvatarElement;
        new (): HTMLLaAvatarElement;
    };
    interface HTMLLaButtonElement extends Components.LaButton, HTMLStencilElement {
    }
    var HTMLLaButtonElement: {
        prototype: HTMLLaButtonElement;
        new (): HTMLLaButtonElement;
    };
    interface HTMLElementTagNameMap {
        "la-avatar": HTMLLaAvatarElement;
        "la-button": HTMLLaButtonElement;
    }
}
declare namespace LocalJSX {
    interface LaAvatar {
        "badge"?: string;
        "image"?: string;
        "size"?: AvatarSizes;
        "text"?: string;
    }
    interface LaButton {
        /**
          * @Prop animated - animate component shadow on hover *
         */
        "animated"?: boolean;
        "size"?: ButtonSizes;
        "variant"?: ButtonVariants;
    }
    interface IntrinsicElements {
        "la-avatar": LaAvatar;
        "la-button": LaButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "la-avatar": LocalJSX.LaAvatar & JSXBase.HTMLAttributes<HTMLLaAvatarElement>;
            "la-button": LocalJSX.LaButton & JSXBase.HTMLAttributes<HTMLLaButtonElement>;
        }
    }
}
